//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeanCounter.ProjectSerializer.Tests.Xml.Serializer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeanCounter.ProjectSerializer.Tests.Xml.Serializer.XmlFiles", typeof(XmlFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://www.github.com/tschouns/beancounter&quot;&gt;
        ///  &lt;VersionInfo&gt;1&lt;/VersionInfo&gt;
        ///  &lt;Backlogs&gt;
        ///    &lt;Backlog&gt;
        ///      &lt;BacklogItems&gt;
        ///        &lt;BacklogItem&gt;
        ///          &lt;ItemId&gt;ab1f3206-602c-457b-8747-5d7f5c3a0fa0&lt;/ItemId&gt;
        ///          &lt;Rank&gt;2&lt;/Rank&gt;
        ///        &lt;/BacklogItem&gt;
        ///        &lt;BacklogItem&gt;
        ///          &lt;ItemId&gt;4557a9cc-360e-4bd1-8ff0-e7c24d40ca9a&lt;/ItemId&gt;
        ///          &lt;Rank&gt;1&lt;/Rank&gt;
        ///        &lt;/BacklogItem&gt;
        ///      &lt;/BacklogItems&gt;
        ///      &lt;Id&gt;38df66 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleProject {
            get {
                return ResourceManager.GetString("SampleProject", resourceCulture);
            }
        }
    }
}
